services:
  - type: web
    name: task-management-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && npm run migrate
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: task_management
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 24h
      - key: JWT_REFRESH_EXPIRE
        value: 7d
      - key: PORT
        value: 5000

databases:
  - name: task_management
    databaseName: task_management_phzk
    user: postgres
